### ISSUE TITLE
Problems using TypeScript for controllers

### ISSUE THREAD

**Issue by ivancevich** [krakenjs/express-enrouten#36]
If I place ```.ts``` files under the controllers directory, they are processed by Kraken and when I try to run the app with ```node index.js``` it does not run.
Of course I'm compiling ```.ts``` into ```.js``` files during development.
Is there a way to ignore anything that is different from ```.js```?
Or at least a way to compile ```.ts``` files with Grunt.
Thanks!

**Comment by jasisk** [comment]
Closed by #51.
